# Generated by Django 2.2.5 on 2019-10-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='hotel_Main_Img',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
    ]
